// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2xGF95FJSFB4bdBmFsnr11AEm1lPTnM',
    appId: '1:689921511529:web:9abef78617c38b6b0bd2f8',
    messagingSenderId: '689921511529',
    projectId: 'fir-ab581',
    authDomain: 'fir-ab581.firebaseapp.com',
    storageBucket: 'fir-ab581.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvj2K0IUPvPF0twG_CzRkwbRE_t9ZcUyQ',
    appId: '1:689921511529:android:665a394f92245edf0bd2f8',
    messagingSenderId: '689921511529',
    projectId: 'fir-ab581',
    storageBucket: 'fir-ab581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyEzEYgX1Yn7jzyuE4CyLy0sppsRmycyQ',
    appId: '1:689921511529:ios:d4ff51e5e801721b0bd2f8',
    messagingSenderId: '689921511529',
    projectId: 'fir-ab581',
    storageBucket: 'fir-ab581.appspot.com',
    iosClientId: '689921511529-f53u4sgmrjhbleks0lh2ecqdhlrka9t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyEzEYgX1Yn7jzyuE4CyLy0sppsRmycyQ',
    appId: '1:689921511529:ios:d4ff51e5e801721b0bd2f8',
    messagingSenderId: '689921511529',
    projectId: 'fir-ab581',
    storageBucket: 'fir-ab581.appspot.com',
    iosClientId: '689921511529-f53u4sgmrjhbleks0lh2ecqdhlrka9t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseblog',
  );
}
